//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Models.myWebservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ViewAll_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback RutTien_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback GuiTien_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback ViewOne_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ktra_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback Insert_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback Update_TKOperationCompleted;
        
        private System.Threading.SendOrPostCallback Delete_TKOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::Models.Properties.Settings.Default.Models_myWebservice_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ViewAll_TKCompletedEventHandler ViewAll_TKCompleted;
        
        /// <remarks/>
        public event RutTien_TKCompletedEventHandler RutTien_TKCompleted;
        
        /// <remarks/>
        public event GuiTien_TKCompletedEventHandler GuiTien_TKCompleted;
        
        /// <remarks/>
        public event ViewOne_TKCompletedEventHandler ViewOne_TKCompleted;
        
        /// <remarks/>
        public event Ktra_TKCompletedEventHandler Ktra_TKCompleted;
        
        /// <remarks/>
        public event Insert_TKCompletedEventHandler Insert_TKCompleted;
        
        /// <remarks/>
        public event Update_TKCompletedEventHandler Update_TKCompleted;
        
        /// <remarks/>
        public event Delete_TKCompletedEventHandler Delete_TKCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ViewAll_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ViewAll_TK() {
            object[] results = this.Invoke("ViewAll_TK", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ViewAll_TKAsync() {
            this.ViewAll_TKAsync(null);
        }
        
        /// <remarks/>
        public void ViewAll_TKAsync(object userState) {
            if ((this.ViewAll_TKOperationCompleted == null)) {
                this.ViewAll_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewAll_TKOperationCompleted);
            }
            this.InvokeAsync("ViewAll_TK", new object[0], this.ViewAll_TKOperationCompleted, userState);
        }
        
        private void OnViewAll_TKOperationCompleted(object arg) {
            if ((this.ViewAll_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewAll_TKCompleted(this, new ViewAll_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/RutTien_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int RutTien_TK(string sotk, int sotien) {
            object[] results = this.Invoke("RutTien_TK", new object[] {
                        sotk,
                        sotien});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void RutTien_TKAsync(string sotk, int sotien) {
            this.RutTien_TKAsync(sotk, sotien, null);
        }
        
        /// <remarks/>
        public void RutTien_TKAsync(string sotk, int sotien, object userState) {
            if ((this.RutTien_TKOperationCompleted == null)) {
                this.RutTien_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRutTien_TKOperationCompleted);
            }
            this.InvokeAsync("RutTien_TK", new object[] {
                        sotk,
                        sotien}, this.RutTien_TKOperationCompleted, userState);
        }
        
        private void OnRutTien_TKOperationCompleted(object arg) {
            if ((this.RutTien_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RutTien_TKCompleted(this, new RutTien_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GuiTien_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GuiTien_TK(string sotk, int sotien) {
            object[] results = this.Invoke("GuiTien_TK", new object[] {
                        sotk,
                        sotien});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GuiTien_TKAsync(string sotk, int sotien) {
            this.GuiTien_TKAsync(sotk, sotien, null);
        }
        
        /// <remarks/>
        public void GuiTien_TKAsync(string sotk, int sotien, object userState) {
            if ((this.GuiTien_TKOperationCompleted == null)) {
                this.GuiTien_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGuiTien_TKOperationCompleted);
            }
            this.InvokeAsync("GuiTien_TK", new object[] {
                        sotk,
                        sotien}, this.GuiTien_TKOperationCompleted, userState);
        }
        
        private void OnGuiTien_TKOperationCompleted(object arg) {
            if ((this.GuiTien_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GuiTien_TKCompleted(this, new GuiTien_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ViewOne_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ViewOne_TK(string sotk) {
            object[] results = this.Invoke("ViewOne_TK", new object[] {
                        sotk});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ViewOne_TKAsync(string sotk) {
            this.ViewOne_TKAsync(sotk, null);
        }
        
        /// <remarks/>
        public void ViewOne_TKAsync(string sotk, object userState) {
            if ((this.ViewOne_TKOperationCompleted == null)) {
                this.ViewOne_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnViewOne_TKOperationCompleted);
            }
            this.InvokeAsync("ViewOne_TK", new object[] {
                        sotk}, this.ViewOne_TKOperationCompleted, userState);
        }
        
        private void OnViewOne_TKOperationCompleted(object arg) {
            if ((this.ViewOne_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ViewOne_TKCompleted(this, new ViewOne_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Ktra_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Ktra_TK(string sotk) {
            object[] results = this.Invoke("Ktra_TK", new object[] {
                        sotk});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Ktra_TKAsync(string sotk) {
            this.Ktra_TKAsync(sotk, null);
        }
        
        /// <remarks/>
        public void Ktra_TKAsync(string sotk, object userState) {
            if ((this.Ktra_TKOperationCompleted == null)) {
                this.Ktra_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnKtra_TKOperationCompleted);
            }
            this.InvokeAsync("Ktra_TK", new object[] {
                        sotk}, this.Ktra_TKOperationCompleted, userState);
        }
        
        private void OnKtra_TKOperationCompleted(object arg) {
            if ((this.Ktra_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ktra_TKCompleted(this, new Ktra_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Insert_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Insert_TK(string sotk, string tentk, int sotien) {
            object[] results = this.Invoke("Insert_TK", new object[] {
                        sotk,
                        tentk,
                        sotien});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Insert_TKAsync(string sotk, string tentk, int sotien) {
            this.Insert_TKAsync(sotk, tentk, sotien, null);
        }
        
        /// <remarks/>
        public void Insert_TKAsync(string sotk, string tentk, int sotien, object userState) {
            if ((this.Insert_TKOperationCompleted == null)) {
                this.Insert_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsert_TKOperationCompleted);
            }
            this.InvokeAsync("Insert_TK", new object[] {
                        sotk,
                        tentk,
                        sotien}, this.Insert_TKOperationCompleted, userState);
        }
        
        private void OnInsert_TKOperationCompleted(object arg) {
            if ((this.Insert_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Insert_TKCompleted(this, new Insert_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Update_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Update_TK(string sotk, string tentk, int sotien) {
            object[] results = this.Invoke("Update_TK", new object[] {
                        sotk,
                        tentk,
                        sotien});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Update_TKAsync(string sotk, string tentk, int sotien) {
            this.Update_TKAsync(sotk, tentk, sotien, null);
        }
        
        /// <remarks/>
        public void Update_TKAsync(string sotk, string tentk, int sotien, object userState) {
            if ((this.Update_TKOperationCompleted == null)) {
                this.Update_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdate_TKOperationCompleted);
            }
            this.InvokeAsync("Update_TK", new object[] {
                        sotk,
                        tentk,
                        sotien}, this.Update_TKOperationCompleted, userState);
        }
        
        private void OnUpdate_TKOperationCompleted(object arg) {
            if ((this.Update_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Update_TKCompleted(this, new Update_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Delete_TK", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Delete_TK(string sotk) {
            object[] results = this.Invoke("Delete_TK", new object[] {
                        sotk});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void Delete_TKAsync(string sotk) {
            this.Delete_TKAsync(sotk, null);
        }
        
        /// <remarks/>
        public void Delete_TKAsync(string sotk, object userState) {
            if ((this.Delete_TKOperationCompleted == null)) {
                this.Delete_TKOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDelete_TKOperationCompleted);
            }
            this.InvokeAsync("Delete_TK", new object[] {
                        sotk}, this.Delete_TKOperationCompleted, userState);
        }
        
        private void OnDelete_TKOperationCompleted(object arg) {
            if ((this.Delete_TKCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Delete_TKCompleted(this, new Delete_TKCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ViewAll_TKCompletedEventHandler(object sender, ViewAll_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewAll_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewAll_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void RutTien_TKCompletedEventHandler(object sender, RutTien_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RutTien_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RutTien_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GuiTien_TKCompletedEventHandler(object sender, GuiTien_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GuiTien_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GuiTien_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ViewOne_TKCompletedEventHandler(object sender, ViewOne_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ViewOne_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ViewOne_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Ktra_TKCompletedEventHandler(object sender, Ktra_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ktra_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ktra_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Insert_TKCompletedEventHandler(object sender, Insert_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Insert_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Insert_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Update_TKCompletedEventHandler(object sender, Update_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Update_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Update_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void Delete_TKCompletedEventHandler(object sender, Delete_TKCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Delete_TKCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Delete_TKCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591